# Generated by Django 4.0.4 on 2022-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=set, to='book_store.author'),
        ),
    ]
