# Generated by Django 4.0.5 on 2022-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('classroom', models.IntegerField()),
                ('teacher', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
