# Generated by Django 4.0.5 on 2022-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='classroom',
            field=models.IntegerField(null=True),
        ),
    ]
