# Generated by Django 4.0.5 on 2022-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_choicechecker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('std', models.IntegerField(null=True)),
                ('mark', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
            ],
        ),
    ]
