# Generated by Django 4.0.5 on 2022-08-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
