# Generated by Django 4.0.4 on 2022-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
