# Generated by Django 4.0.5 on 2022-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/profile.jpg', null=True, upload_to=''),
        ),
    ]
